// Generated by CoffeeScript 1.3.1
(function() {
  var Employee, Person, e;

  Person = function(name, age) {
    this.name = name;
    return this.age = age;
  };

  Person.prototype.description = function() {
    return "" + this.name + " " + this.age;
  };

  Employee = function(name, age, sal) {
    this.sal = sal;
    return Person.call(this, name, age);
  };

  Employee.prototype = new Person();

  Employee.prototype.description = function() {
    var genericDesc;
    genericDesc = Person.prototype.description.call(this);
    return "" + this.genericDesc + " " + this.sal;
  };

  e = new Employee("foo", 25, 25000);

  console.log(e.description());

}).call(this);
